site_name: photos.network
site_url: https://photos.network
repo_url: https://github.com/photos-network
repo_name: photos.network
edit_uri: photos.network/edit/development/docs/
site_description: "https://photos.network is an open source project for self hosted photo management."
site_author: "Stürmer, Benjamin"
copyright: 'Copyright &copy; 2020 <a href="https://photos.network">Photos network developers</a>'

extra_css:
  - _css/extra.css

extra_javascript:
  - _js/extra.js

extra:
  version: 1.0.0
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/photosnetwork
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.cloud/@photos

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

strict: true

# Navigation
nav:
  - "Home": "index.md"
  - "Installation":
      - "Docker": "installation/docker.md"
      - "Standalone": "installation/index.md"
  - "Documentation":
      - "Configuration": "documentation/index.md"
      - "Addons": "documentation/addons.md"

# Theme
theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: preference
      primary: indigo
      accent: pink

  # disable font loading to comply GDPR
  font: false

  icon:
    logo: material/image
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tabs
