site_name: photos.network
site_url: https://photos.network
repo_url: https://github.com/photos-network
repo_name: photos.network
site_description: "https://photos.network is an open source project for self hosted photo management."
site_author: "Stürmer, Benjamin"
copyright: 'Copyright &copy; 2020 <a href="https://photos.network">Photos network developers</a>'

extra_css:
  - _css/extra.css

extra_javascript:
  - _js/extra.js

extra:
  version: 1.0
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/thebino/photos
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/photos.network

markdown_extensions:
  - attr_list
  - admonition

strict: true

# Navigation
nav:
  - 'Home': 'index.md'
  - 'Installation':
      - 'Standalone': 'installation/index.md'
      - 'Docker': 'installation/docker.md'
  - 'Documentation':
      - 'Configuration': 'documentation/index.md'
  - 'Development': https://developers.photos.network


# Theme
theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: preference
      primary: indigo
      accent: pink

  # disable font loading to comply GDPR
  font: false

  icon:
    logo: material/image
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tabs
