name: build and deploy with zola

on:
  workflow_dispatch:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
        with:
          submodules: "recursive"
          fetch-depth: 0       # Fetch all history for .GitInfo and .Lastmod
      
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          OUT_DIR: docs
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

